export enum ErrorMap {
  CANNOT_CREATE_MODEL = 'CANNOT_CREATE_MODEL',
  CANNOT_FIND_MODEL = 'CANNOT_FIND_MODEL',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  DIRECTION_EXISTS = 'DIRECTION_EXISTS',
  USER_NOT_FOUND = 'User not found in request',
}
